### ISSUE TITLE
Missing ill role in content.opf

### ISSUE THREAD

**Issue by robinwhittleton** [drgrigg/ulysses-s-grant_personal-memoirs-of-u-s-grant#1]
I’m guessing Grant drew the images himself?

**Comment by drgrigg** [comment]
Oh, surely not. Many were official maps drawn up by the U.S. government. Some of them have inscriptions to that effect. See illustration-4 for example. I'm sure that talented as Grant was, he wasn't a cartographer or illustrator.

I've left the 'ill' role blank because it's not at at clear who to name there, but I'm sure it shouldn't be Grant himself.

**Comment by robinwhittleton** [comment]
Fair enough! (just filed https://github.com/standardebooks/tools/pull/110 for the other lint issue)
